version: '3'

services:

  api:
    container_name: google-map-api_web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${API_PORT}:8083
    depends_on:
      - memcached
      - mongodb_log
    networks:
      - apiNetwork

  memcached:
    container_name: google-map-api_memcached
    image: memcached:latest
    ports:
      - ${MEMCACHED_PORT}:11211
    networks:
      - apiNetwork

  mongodb_log:
    container_name: google-map-api_mongodb_log
    image: mongo:latest
    command: mongod --port ${MONGODB_LOGGER_PORT}
    ports:
      - ${MONGODB_LOGGER_PORT}:27017
    networks:
      - apiNetwork

networks:
  apiNetwork: