version: '3'

services:

  api:
    container_name: google-map-api_web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${API_PORT}:8083
    networks:
      - apiNetwork

  memcached:
    container_name: google-map-api_memcached
    image: memcached:latest
    ports:
      - ${MEMCACHED_PORT}:11211
    networks:
      - apiNetwork

networks:
  apiNetwork: